apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: online-boutique

resources:
- ../../../base

images:
- name: frontend
  newName: 491243661002.dkr.ecr.us-east-1.amazonaws.com/online-boutique-aws-dev-online_boutique
  newTag: frontend-01410680647e9530f63a44c14ac40f0ec72a7779
