apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: online-boutique

resources:
- ../../../base

images:
- name: frontend
  newName: 491243661002.dkr.ecr.us-east-1.amazonaws.com/online-boutique-aws-dev-online_boutique
  newTag: frontend-42477f1647adb52698f6a313ef318800a94c3b84
